Metrics/LineLength:
  Max: 130
Metrics/AbcSize:
  Max: 40
Metrics/MethodLength:
  Max: 25
Metrics/ClassLength:
  Max: 110
Metrics/PerceivedComplexity:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 15